apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: netflix-app
  template:
    metadata:
      labels:
        name: netflix-app
    spec:
      containers:
        - name: netflix-app
          image: yormengh/netflix
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-app
spec:
  selector:
    name: netflix-app
  ports:
    - port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /second
            pathType: Prefix
            backend:
              service:
                name: netflix-app
                port:
                  number: 8080
